// <auto-generated />
using System;
using LUMAApp.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LUMAApp.Migrations
{
    [DbContext(typeof(LmaContext))]
    partial class LmaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LUMAApp.Entities.EmpMaster", b =>
                {
                    b.Property<string>("EmpId")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("emp_id");

                    b.Property<string>("Dept")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("dept");

                    b.Property<string>("Desgn")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("desgn");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<DateTime?>("Doj")
                        .HasColumnType("date")
                        .HasColumnName("DOJ");

                    b.Property<string>("EmpName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("emp_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("gender")
                        .IsFixedLength();

                    b.HasKey("EmpId")
                        .HasName("PK__emp_mast__1299A86157AF7BC0");

                    b.ToTable("emp_master", (string)null);
                });

            modelBuilder.Entity("LUMAApp.Entities.EmployeeCardDetail", b =>
                {
                    b.Property<string>("EmpId")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("emp_id");

                    b.Property<string>("LoanId")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("loan_id");

                    b.Property<DateTime?>("CardIssueDate")
                        .HasColumnType("date")
                        .HasColumnName("card_issue_date");

                    b.HasKey("EmpId", "LoanId")
                        .HasName("PK__employee__4886D13468744E9C");

                    b.HasIndex("LoanId");

                    b.ToTable("employee_card_details", (string)null);
                });

            modelBuilder.Entity("LUMAApp.Entities.EmployeeIssueDetail", b =>
                {
                    b.Property<string>("IssueId")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("issue_id");

                    b.Property<string>("EmpId")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("emp_id");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("ItemId")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("item_id");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.HasKey("IssueId")
                        .HasName("PK__employee__D6185C39B647C266");

                    b.HasIndex("EmpId");

                    b.HasIndex("ItemId");

                    b.ToTable("employee_issue_details", (string)null);
                });

            modelBuilder.Entity("LUMAApp.Entities.ItemMaster", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemCategory")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("item_category");

                    b.Property<string>("ItemDescp")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("item_descp");

                    b.Property<string>("ItemMake")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("item_make");

                    b.Property<string>("ItemStatus")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("item_status")
                        .IsFixedLength();

                    b.Property<int?>("ItemValuation")
                        .HasColumnType("int")
                        .HasColumnName("item_valuation");

                    b.HasKey("ItemId")
                        .HasName("PK__item_mas__52020FDD153DD1E2");

                    b.HasIndex("ItemCategory");

                    b.ToTable("item_master", (string)null);
                });

            modelBuilder.Entity("LUMAApp.Entities.LoanCardMaster", b =>
                {
                    b.Property<string>("LoanId")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("loan_id");

                    b.Property<int?>("DurationYears")
                        .HasColumnType("int")
                        .HasColumnName("duration_years");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("loan_type");

                    b.HasKey("LoanId")
                        .HasName("PK__loan_car__A1F79554DD11A340");

                    b.HasIndex(new[] { "LoanType" }, "SET_UNIQUE_LOAN_TYPE")
                        .IsUnique();

                    b.ToTable("loan_card_master", (string)null);
                });

            modelBuilder.Entity("LUMAApp.Entities.EmployeeCardDetail", b =>
                {
                    b.HasOne("LUMAApp.Entities.EmpMaster", "Emp")
                        .WithMany("EmployeeCardDetails")
                        .HasForeignKey("EmpId")
                        .IsRequired()
                        .HasConstraintName("FK__employee___emp_i__36B12243");

                    b.HasOne("LUMAApp.Entities.LoanCardMaster", "Loan")
                        .WithMany("EmployeeCardDetails")
                        .HasForeignKey("LoanId")
                        .IsRequired()
                        .HasConstraintName("FK__employee___loan___37A5467C");

                    b.Navigation("Emp");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LUMAApp.Entities.EmployeeIssueDetail", b =>
                {
                    b.HasOne("LUMAApp.Entities.EmpMaster", "Emp")
                        .WithMany("EmployeeIssueDetails")
                        .HasForeignKey("EmpId")
                        .HasConstraintName("FK__employee___emp_i__3A81B327");

                    b.HasOne("LUMAApp.Entities.ItemMaster", "Item")
                        .WithMany("EmployeeIssueDetails")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK__employee___item___3B75D760");

                    b.Navigation("Emp");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("LUMAApp.Entities.ItemMaster", b =>
                {
                    b.HasOne("LUMAApp.Entities.LoanCardMaster", "ItemCategoryNavigation")
                        .WithMany("ItemMasters")
                        .HasForeignKey("ItemCategory")
                        .HasPrincipalKey("LoanType")
                        .HasConstraintName("FK_LOAN_TYPE_ITEM_CATEGORY");

                    b.Navigation("ItemCategoryNavigation");
                });

            modelBuilder.Entity("LUMAApp.Entities.EmpMaster", b =>
                {
                    b.Navigation("EmployeeCardDetails");

                    b.Navigation("EmployeeIssueDetails");
                });

            modelBuilder.Entity("LUMAApp.Entities.ItemMaster", b =>
                {
                    b.Navigation("EmployeeIssueDetails");
                });

            modelBuilder.Entity("LUMAApp.Entities.LoanCardMaster", b =>
                {
                    b.Navigation("EmployeeCardDetails");

                    b.Navigation("ItemMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
